// app/speaking/data.ts
export const tasks = [
  {
    id: 1,
    title: 'عرّف نفسك في دقيقة',
    subtitle: 'Self Introduction',
    hint: 'اسمك، شغلك، هواياتك، وأهدافك.',
    tips: ['ابدأ بـ My name is...', 'اذكر تخصصك بـ I work as...', 'أضف هواية واحدة على الأقل'],
    level: 'A1',
    duration: '1 دقيقة',
    xp: 30,
    category: 'تعارف',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=80',
    tag: 'للمبتدئين',
    fullDescription: 'تخيل إنك بتقابل شخص جديد لأول مرة. عرّف نفسك بطريقة طبيعية: اسمك، إيه شغلك، إيه هواياتك، وإيه أهدافك في الفترة الجاية. حاول تتكلم لمدة دقيقة كاملة بدون توقف.',
    sampleAnswer: 'My name is Ahmed. I work as a software engineer. In my free time, I love playing football and reading books. My goal is to improve my English speaking skills.',
  },
  {
    id: 2,
    title: 'احكِ عن يومك',
    subtitle: 'Describe Your Day',
    hint: 'رتّب أحداث يومك بالأزمنة الصحيحة.',
    tips: ['استخدم الماضي البسيط', 'أضف تفاصيل صغيرة', 'استخدم then / after that'],
    level: 'A2',
    duration: '2 دقيقة',
    xp: 40,
    category: 'حياة يومية',
    image: 'https://images.unsplash.com/photo-1506784365847-bbad939e9335?w=500&q=80',
    tag: null,
    fullDescription: 'احكي بالتفصيل عن يومك العادي من الصبح للمساء. إيه أول حاجة عملتها لما صحيت؟ إيه اللي أكلته؟ قابلت مين؟ إيه أحسن حاجة حصلت في يومك؟',
    sampleAnswer: 'Yesterday, I woke up at 7 AM. First, I took a shower and had breakfast. Then, I went to work by bus. After work, I met my friends at a cafe. We talked for two hours. Finally, I went home and watched TV before sleeping.',
  },
  {
    id: 3,
    title: 'موقف في العمل',
    subtitle: 'Workplace Scenario',
    hint: 'تواصل مهني مختصر مع مديرك أو زميلك.',
    tips: ['ابدأ بـ I wanted to discuss...', 'كن مباشراً ومحترماً', 'استخدم Could you... بدل Can you...'],
    level: 'B1',
    duration: '3 دقائق',
    xp: 55,
    category: 'عمل',
    image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=500&q=80',
    tag: 'الأكثر شعبية',
    fullDescription: 'تخيل إنك محتاج تطلب إجازة من مديرك أو تناقش مشروع مع زميلك. استخدم لغة مهنية محترمة.',
    sampleAnswer: 'Good morning, Mr. John. I wanted to discuss my vacation days. Could I take a week off next month? I have some family plans. I will make sure to finish all my tasks before that.',
  },
  {
    id: 4,
    title: 'آرائك في موضوع',
    subtitle: 'Express Your Opinion',
    hint: 'عبّر عن رأيك في موضوع اجتماعي أو ثقافي.',
    tips: ['ابدأ بـ In my opinion...', 'أضف سبباً بـ because', 'اختم بـ That\'s why I think...'],
    level: 'B1',
    duration: '2 دقيقة',
    xp: 50,
    category: 'نقاش',
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=500&q=80',
    tag: null,
    fullDescription: 'عبر عن رأيك في موضوع زي "السفر" أو "الدراسة عن بعد" أو "العمل من المنزل".',
    sampleAnswer: 'In my opinion, working from home is very beneficial. First, it saves time and money because you don\'t need to commute. Second, you can work in a comfortable environment. That\'s why I think many companies should offer this option.',
  },
  {
    id: 5,
    title: 'وصف صورة',
    subtitle: 'Describe a Picture',
    hint: 'صف ما تراه بتفاصيل دقيقة وأسلوب سلس.',
    tips: ['ابدأ بـ In this picture I can see...', 'وصف الخلفية والمقدمة', 'استخدم there is / there are'],
    level: 'A2',
    duration: '90 ثانية',
    xp: 35,
    category: 'حياة يومية',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=500&q=80',
    tag: null,
    fullDescription: 'صف صورة بالتفاصيل: إيه اللي شايفه في الأمام؟ إيه في الخلفية؟ الناس بيعملوا إيه؟ الألوان إيه؟',
    sampleAnswer: 'In this picture, I can see a beautiful beach. There is clear blue water and white sand. In the background, there are some mountains. There are two people sitting under an umbrella. They look happy and relaxed.',
  },
  {
    id: 6,
    title: 'مقابلة عمل',
    subtitle: 'Job Interview',
    hint: 'جاوب على أسئلة المقابلة باحترافية.',
    tips: ['Why should we hire you?', 'What are your weaknesses?', 'جاوب بـ STAR method'],
    level: 'B2',
    duration: '5 دقائق',
    xp: 70,
    category: 'عمل',
    image: 'https://images.unsplash.com/photo-1565688534245-05d6b5be184a?w=500&q=80',
    tag: 'تحدي',
    fullDescription: 'جاوب على أسئلة المقابلة الشهيرة: ليه عايز الشغل؟ إيه نقاط قوتك وضعفك؟ ليه نختارك أنت بالذات؟',
    sampleAnswer: 'I believe I am a good fit for this position because I have 3 years of experience in this field. My biggest strength is problem-solving. Regarding weaknesses, sometimes I am too perfectionist, but I am working on time management.',
  },
  {
    id: 7,
    title: 'نقاش أكاديمي',
    subtitle: 'Academic Discussion',
    hint: 'ناقش موضوعاً علمياً أو أكاديمياً بأسلوب رسمي.',
    tips: ['استخدم Furthermore / Moreover', 'أضف أدلة وإحصائيات وهمية', 'ختم بـ To conclude...'],
    level: 'C1',
    duration: '5 دقائق',
    xp: 80,
    category: 'أكاديمي',
    image: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=500&q=80',
    tag: 'متقدم',
    fullDescription: 'ناقش موضوع أكاديمي زي "تأثير التكنولوجيا على التعليم" بأسلوب رسمي.',
    sampleAnswer: 'Technology has significantly transformed education. Furthermore, online learning platforms have made education accessible to millions. According to recent studies, 70% of students prefer blended learning. To conclude, technology will continue to shape the future of education.',
  },
  {
    id: 8,
    title: 'قصة قصيرة',
    subtitle: 'Tell a Story',
    hint: 'احكِ قصة حقيقية أو خيالية بتسلسل منطقي.',
    tips: ['ابدأ بـ Once upon a time / Last year...', 'استخدم suddenly / unfortunately', 'ختم بدرس أو نتيجة'],
    level: 'B1',
    duration: '3 دقائق',
    xp: 55,
    category: 'إبداع',
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=500&q=80',
    tag: 'جديد',
    fullDescription: 'احكي قصة قصيرة: إيه اللي حصل؟ فين؟ إمتى؟ إيه المشكلة؟ إيه الحل؟ إيه اللي اتعلمته؟',
    sampleAnswer: 'Last year, I traveled to Aswan with my family. Unfortunately, we lost our way to the hotel. Suddenly, a kind local man helped us find the place. It was a memorable adventure, and I learned that Egyptian people are very helpful.',
  },
  {
    id: 9,
    title: 'حوار في المطعم',
    subtitle: 'Restaurant Roleplay',
    hint: 'العب دور الزبون والطلب من النادل.',
    tips: ["I'd like to order...", 'Could I have the menu?', 'Is this dish spicy?'],
    level: 'A1',
    duration: '2 دقيقة',
    xp: 30,
    category: 'حياة يومية',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=500&q=80',
    tag: null,
    fullDescription: 'تخيل إنك في مطعم وعايز تطلب أكل. إزاي تطلب؟ إزاي تسأل عن الأكل؟ إزاي تطلب الحساب؟',
    sampleAnswer: 'Excuse me, could I have the menu please? Thank you. I would like to order the grilled chicken. Is this dish spicy? Okay, I will take it. Also, can I have a glass of water? Please bring the bill when you can.',
  },
]

export const levels = [
  { label: 'A1', desc: 'مبتدئ', color: { bg: '#dcfce7', text: '#15803d', border: '#bbf7d0' } },
  { label: 'A2', desc: 'أساسي', color: { bg: '#d1fae5', text: '#065f46', border: '#a7f3d0' } },
  { label: 'B1', desc: 'متوسط', color: { bg: '#dbeafe', text: '#1d4ed8', border: '#bfdbfe' } },
  { label: 'B2', desc: 'فوق المتوسط', color: { bg: '#ede9fe', text: '#6d28d9', border: '#ddd6fe' } },
  { label: 'C1', desc: 'متقدم', color: { bg: '#fce7f3', text: '#9d174d', border: '#fbcfe8' } },
]